# Policy

## Basic Requirements for Paper Submissions {.unnumbered}

The EcoEvoRxiv server publishes preprints, postprints, reports, and data papers that contribute to the understanding of and advances in Ecology, Evolutionary Biology, Conservation Biology, and related fields.

EcoEvoRxiv welcomes manuscripts based on empirical and simulation data, as well as literature reviews, theory, and opinion, perspective, and comment pieces.

EcoEvoRxiv hosts manuscripts:

-   Written in English, Spanish, Portuguese, French, Italian, German, Dutch, Greek, Korean or Japanese
-   Of high quality with regard to structure, data presentation, and validity of conclusions
-   From the scientific disciplines of Ecology, Evolutionary Biology, Conservation Biology, or related fields
-   Containing a title, author name(s) and affiliation(s)
-   Providing details of correspondence (at minimum an email address) for at least one author
-   Free from personal attacks

*Manuscripts will not be hosted when violations of these policies are detected.*

Empirical and theoretical manuscripts will be assessed by at least one editor, whereas an opinion or review article may be assessed by two or more editors.

If the submitted manuscript is missing a title page or details of correspondence, authors are requested to submit an updated version of the manuscript before further assessment. If there is any doubt whether the submitted manuscript fits within the scope of Ecology, Evolutionary Biology, Conservation Biology, or related fields, authors are requested a clarification or justification for why they deem their work fitting for EcoEvoRxiv. In both instances, if authors do not respond *within 2 weeks*, the manuscript will be rejected.

For postprints, it is the authors’ responsibility to connect their postprint to the published version of the article and ensure that the postprint adheres to the publisher’s copyright and self-archiving policy. Publisher policies on self-archiving of preprints and postprints can be found on the Sherpa-Romeo webpage.

Preprints can be withdrawn if serious issues with a manuscript are identified after the preprint has been published. For example, EcoEvoRxiv reserves the right to withdraw a preprint if requested by the authors (e.g., due to significant errors or omissions), in the event of conflicts among authors or third parties (e.g., disagreement on authorship or data ownership), or in instances where there is evidence of scientific misconduct (e.g., plagiarism, data fabrication or falsification). Preprints can be resubmitted if errors are corrected and/or conflicts resolved.

Like other preprint servers, EcoEvoRxiv is inclined to reject submissions that are found to be posted on other platforms. Having the same preprint posted on multiple platforms, authors may find it difficult to keep the different versions on the different platforms updated; may cause issues with citations and other usage metrics, making it difficult to track downstream impacts of the preprint; and creates unnecessary redundancy in academic literature.

EcoEvoRxiv may update this publication policy at any time.

## Licensing {.unnumbered}

One of the following re-use licenses must be applied to your submission:

-   [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) - Creative Commons Attribution 4.0 International
-   [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) - Creative Commons Attribution-Non-Commercial 4.0 International
-   [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/) - Creative Commons Attribution-No Derivatives 4.0 International
-   [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) - Creative Commons Attribution-Share Alike 4.0 International
-   [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) - Creative Commons Attribution-Non-Commercial-No Derivatives 4.0 International
-   [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) - Creative Commons Attribution-Non-Commercial-Share Alike 4.0 International
-   No CC license - No Creative Commons license will be applied

Not sure which license to choose? [Answer the questions at Creative Commons' license selector](https://creativecommons.org/choose/) to find the right license, or see this [FAQ from arXiv](https://arxiv.org/help/license) on licenses and preprints.
