---
title: "EcoEvoRxiv - Home"
layout: default
output: 
  bookdown::html_document2:
    code_folding: hide
    number_sections: no
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

## Welcome to EcoEvoRxiv

<summary style=font-size:18px> EcoEvoRxiv is an open-access pre-print server for ecological and evolutionary research. Our goal is to facilitate researchers sharing their findings before formal publication by providing a platform for cutting-edge research in the fields of ecology and evolutionary biology. </summary>    

## Why use a pre-print server?

#### They’re quick!
  <summary style=font-size:14px> Preprints are a way of disseminating your findings before a long [peer-reviewed process](https://www.nature.com/articles/530148a). This means your work won’t be out of date by the time people read it. </summary>
  
#### Open access
  <summary style=font-size:14px> Your work can reach researchers and others who do not have access to pay walled publications. </summary>   

#### Improved science
  <summary style=font-size:14px> Once you’ve posted a preprint, other researchers may offer feedback on it via email or social media.It is a chance to catch mistakes, improve clarity and grow, before it’s committed to publication. </summary>  

#### Citations 
  <summary style=font-size:14px> Preprints can be cited, and can be used to establish precedence of your work. </summary>  


## How to use EcoEvoRxiv

#### Basic rules
- Publication rules and Policy

- Publication times


#### Submitting a manuscript
- How to? -- VIDEO?? (I have no idea how to do it)


#### Updating or modifying your manuscript
- How to? -- VIDEO?? (I have no idea how to do it)


#### What's next?
- Communcation and advertising

- Peer-review process??


## Contact Us

For inquiries, please reach out to [info@ecoevorxiv.org](mailto:info@ecoevorxiv.org).

## Follow Us

Stay updated by following us on:
[Twitter](https://twitter.com/EcoEvoRxiv)
